// File generated by FlutterFire CLI.
// Arquivo de configuração do Firebase - Normalmente gerado automaticamente
// Este é um arquivo simulado para demonstração

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Configurações padrão do Firebase para o aplicativo Flutter.
/// 
/// Em um projeto real, este arquivo seria gerado automaticamente pelo FlutterFire CLI
/// após a configuração do projeto no Firebase Console.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Para um aplicativo real, você teria diferentes configurações para cada plataforma
    // Web, Android, iOS, macOS, etc.
    
    // Como este é um exemplo, usaremos valores fictícios
    return const FirebaseOptions(
      apiKey: 'AIzaSyCJIY5XCAizL4zUI0JE41s_MhKqLbqDoEI',
      appId: '1:1015573680868:android:763f9dddbff7edf96d92f1',
      messagingSenderId: '1015573680868',
      projectId: 'login-78623',
      authDomain: 'login-78623.firebaseapp.com',
      storageBucket: 'login-78623.firebasestorage.app',
    );
  }
}
